server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookapp
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl.auto: update

logging.level.root: DEBUG
